FROM neo4j:latest

ARG LOCAL_NEO4J_USERNAME
ARG LOCAL_NEO4J_PASSWORD

ENV NEO4J_AUTH=${LOCAL_NEO4J_USERNAME}/${LOCAL_NEO4J_PASSWORD}
ENV NEO4J_initial_dbms_default__database=captures

EXPOSE 7474 7473 7687

CMD ["neo4j"]