"""Lightweight public contracts for the JAWS research workbench."""

from .captures import (
    ACTIVE_CAPTURE_STATES,
    TERMINAL_CAPTURE_STATES,
    CaptureRecord,
    ObservationScope,
    ProfileIdentity,
    capture_scope_id,
)
from .enrichment import EnrichmentRecord, EntityMetadata, ResearcherAnnotation, normalized_ip
from .enums import (
    CaptureSourceKind,
    CaptureState,
    EnrichmentStatus,
    EntityType,
    ErrorCategory,
    MeasurementUnit,
    ObservationScopeKind,
    OutlierStatus,
    ProfileStatus,
    ReferenceKind,
    RunState,
    ScoreDirection,
)
from .errors import DomainError
from .identifiers import (
    CanonicalDigest,
    CaptureId,
    DatasetId,
    EntityId,
    ExperimentId,
    FindingId,
    ObservationScopeId,
    RunId,
    SchemaVersion,
)
from .inspection import EndpointInspection, EndpointPacketSample, EndpointPeerTraffic
from .measurements import Measurement, bytes_count, interval_seconds, packet_count, ratio
from .packets import PacketRecord
from .profiles import EndpointProfile, ProfileScopeSummary
from .protocols import Clock, IdGenerator
from .ranking import ScoredEntity, deterministic_ranking
from .results import Failure, Result, Success, legacy_failure, legacy_success, structured_envelope
from .secrets import REDACTED, UNSET, Secret
from .serialization import canonical_digest, canonical_json, primitive
from .specifications import (
    EntityDefinition,
    EvidencePointer,
    ExperimentSpec,
    ObservationWindow,
    RankedFinding,
    RankerSpec,
    ReferenceSpec,
    RepresentationSpec,
    Score,
    VersionedSpec,
)
from .time import CAPTURE_TRANSITIONS, RUN_TRANSITIONS, normalize_utc, require_transition, utc_text

__all__ = [
    "CAPTURE_TRANSITIONS",
    "ACTIVE_CAPTURE_STATES",
    "REDACTED",
    "RUN_TRANSITIONS",
    "UNSET",
    "CanonicalDigest",
    "CaptureId",
    "CaptureRecord",
    "CaptureSourceKind",
    "CaptureState",
    "Clock",
    "DatasetId",
    "DomainError",
    "EntityDefinition",
    "EntityId",
    "EntityType",
    "EndpointProfile",
    "EndpointInspection",
    "EndpointPacketSample",
    "EndpointPeerTraffic",
    "EnrichmentRecord",
    "EntityMetadata",
    "EnrichmentStatus",
    "ErrorCategory",
    "EvidencePointer",
    "ExperimentId",
    "ExperimentSpec",
    "Failure",
    "FindingId",
    "IdGenerator",
    "Measurement",
    "MeasurementUnit",
    "ObservationWindow",
    "ObservationScope",
    "ObservationScopeId",
    "ObservationScopeKind",
    "OutlierStatus",
    "PacketRecord",
    "RankedFinding",
    "RankerSpec",
    "ReferenceKind",
    "ReferenceSpec",
    "RepresentationSpec",
    "Result",
    "RunId",
    "RunState",
    "SchemaVersion",
    "Score",
    "ScoreDirection",
    "ScoredEntity",
    "ProfileIdentity",
    "ProfileStatus",
    "ProfileScopeSummary",
    "ResearcherAnnotation",
    "Secret",
    "Success",
    "TERMINAL_CAPTURE_STATES",
    "VersionedSpec",
    "bytes_count",
    "capture_scope_id",
    "canonical_digest",
    "canonical_json",
    "deterministic_ranking",
    "interval_seconds",
    "legacy_failure",
    "legacy_success",
    "normalize_utc",
    "normalized_ip",
    "packet_count",
    "primitive",
    "ratio",
    "require_transition",
    "structured_envelope",
    "utc_text",
]
