services:
  neo4j:
    image: neo4j:latest
    environment:
      NEO4J_AUTH: ${LOCAL_NEO4J_USERNAME}/${LOCAL_NEO4J_PASSWORD}
      NEO4J_initial_dbms_default__database: captures
    network_mode: "host"
    privileged: true
    expose:
      - 7474
      - 7473
      - 7687

  jaws:
    build:
      context: .
      dockerfile: Dockerfile.jaws
    environment:
      LOCAL_NEO4J_URI: ${LOCAL_NEO4J_URI}
      LOCAL_NEO4J_USERNAME: ${LOCAL_NEO4J_USERNAME}
      LOCAL_NEO4J_PASSWORD: ${LOCAL_NEO4J_PASSWORD}
      IPINFO_API_KEY: ${IPINFO_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      HUGGINGFACE_KEY: ${HUGGINGFACE_KEY}
      DOWNLOAD_FOLDER: /home
      # This does not use the host systems DOWNLOAD_FOLDER, but instead uses the container's /home directory
    depends_on:
      - neo4j
    network_mode: "host"
    privileged: true
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ${DOWNLOAD_FOLDER}:/home
      # This uses the host systems DOWNLOAD_FOLDER, but mounts it to the container's /home directory
      # This allows the files created by the container to be downloaded to the host system


# To enter a bash shell in the jaws container, run the following command:
# docker ps
# docker exec -it <container_id> bash
