services:
  jaws:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEO4J_URI: ${NEO4J_URI}
        NEO4J_USERNAME: ${NEO4J_USERNAME}
        NEO4J_PASSWORD: ${NEO4J_PASSWORD}
        IPINFO_API_KEY: ${IPINFO_API_KEY}
        OPENAI_API_KEY: ${OPENAI_API_KEY}
        HUGGINGFACE_API_KEY: ${HUGGINGFACE_API_KEY}
    network_mode: "host"
    privileged: true
    ports:
      - "5297:5297"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ${JAWS_FINDER_ENDPOINT}:/home
      # This uses the host systems JAWS_FINDER_ENDPOINT, but mounts it to the container's /home directory
      # This allows the files created by the container to be downloaded to the host system