services:
  jaws:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NEO4J_URI: ${NEO4J_URI}
      NEO4J_USERNAME: ${NEO4J_USERNAME}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
      IPINFO_API_KEY: ${IPINFO_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      HUGGINGFACE_API_KEY: ${HUGGINGFACE_API_KEY}
      JAWS_FINDER_ENDPOINT: /home
      # This does not use the host systems DOWNLOAD_FOLDER, but instead uses the container's /home directory
    network_mode: "host"
    privileged: true
    command: ["tail", "-f", "/dev/null"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ${JAWS_FINDER_ENDPOINT}:/home
      # This uses the host systems JAWS_FINDER_ENDPOINT, but mounts it to the container's /home directory
      # This allows the files created by the container to be downloaded to the host system


# To enter a bash shell in the jaws container, run the following command:
# docker ps
# docker exec -it <container_id> bash
