#!/usr/bin/env python3
"""Generate deterministic CLI and MCP reference pages from shipped contracts."""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import tomllib
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Any

REPOSITORY = Path(__file__).resolve().parents[1]
PYPROJECT = REPOSITORY / "pyproject.toml"
MCP_CONTRACT = REPOSITORY / "jaws_mcp" / "contracts" / "v2" / "tool-contracts.json"

MODULES = {
    "jaws-admin": "jaws.administration_cli",
    "jaws-benchmark": "jaws.benchmark_cli",
    "jaws-capture": "jaws.jaws_capture",
    "jaws-compute": "jaws.jaws_compute",
    "jaws-evidence": "jaws.evidence_cli",
    "jaws-finder": "jaws.jaws_finder",
    "jaws-ipinfo": "jaws.jaws_ipinfo",
    "jaws-lab": "jaws_lab.cli",
    "jaws-mcp": "jaws_mcp.server",
    "jaws-research": "jaws.research_cli",
    "jaws-retention": "jaws.retention_cli",
    "jaws-runtime": "jaws.runtime_cli",
    "jaws-schema": "jaws.storage.cli",
    "jaws-utils": "jaws.jaws_utils",
}


def _help(command: str, module: str) -> str:
    result = subprocess.run(
        (sys.executable, "-m", module, "--help"),
        cwd=REPOSITORY,
        check=False,
        capture_output=True,
        text=True,
        timeout=30,
    )
    if result.returncode != 0:
        raise RuntimeError(f"{command} --help failed: {result.stderr.strip()}")
    output = result.stdout.strip()
    if not output:
        raise RuntimeError(f"{command} --help produced no output")
    return output


def cli_reference() -> str:
    document = tomllib.loads(PYPROJECT.read_text(encoding="utf-8"))
    scripts = document["project"]["scripts"]
    assert isinstance(scripts, dict)
    expected = set(MODULES) | {"jaws-guide"}
    if set(scripts) != expected:
        raise RuntimeError("CLI reference module inventory differs from project scripts")
    lines = [
        "# CLI reference",
        "",
        "Generated by `python scripts/generate_reference.py` from the 3.0 entry-point "
        "inventory and each parser's `--help` output. `jaws-guide` is narrative guidance "
        "and is intentionally represented by the workflow documentation rather than a "
        "parser snapshot.",
        "",
    ]
    for command, module in sorted(MODULES.items()):
        lines.extend((f"## `{command}`", "", "```text", _help(command, module), "```", ""))
    return "\n".join(lines).rstrip() + "\n"


def _mapping(value: object, name: str) -> Mapping[str, Any]:
    if not isinstance(value, Mapping):
        raise RuntimeError(f"{name} must be an object")
    return value


def _field_names(schema: Mapping[str, Any]) -> str:
    properties = schema.get("properties", {})
    if not isinstance(properties, Mapping) or not properties:
        return "—"
    required = schema.get("required", [])
    required_names = set(required) if isinstance(required, list) else set()
    return ", ".join(
        f"`{name}`{'*' if name in required_names else ''}" for name in sorted(properties)
    )


def mcp_reference() -> str:
    document = _mapping(json.loads(MCP_CONTRACT.read_text(encoding="utf-8")), "contract")
    tools = _mapping(document.get("tools"), "tools")
    definitions = _mapping(document.get("$defs"), "$defs")
    lines = [
        "# MCP v2 contract reference",
        "",
        "Generated by `python scripts/generate_reference.py` from "
        "`jaws_mcp/contracts/v2/tool-contracts.json`. A trailing `*` marks a required "
        "input. The JSON contract is authoritative.",
        "",
        f"- Tool schema: `{document.get('schema_version')}`",
        f"- Research API schema: `{document.get('api_schema_version')}`",
        f"- Capability version: `{document.get('capability_version')}`",
        "",
        "| Tool | Policy | Inputs |",
        "| --- | --- | --- |",
    ]
    for name, raw in sorted(tools.items()):
        contract = _mapping(raw, f"tool {name}")
        schema = _mapping(contract.get("input_schema"), f"tool {name} input")
        reference = schema.get("$ref")
        if isinstance(reference, str) and reference.startswith("#/$defs/"):
            schema = _mapping(definitions.get(reference.rsplit("/", 1)[-1]), reference)
        lines.append(f"| `{name}` | `{contract.get('policy')}` | {_field_names(schema)} |")
    errors = document.get("error_codes", [])
    if isinstance(errors, list):
        lines.extend(("", "## Stable error codes", "", ", ".join(f"`{item}`" for item in errors)))
    return "\n".join(lines).rstrip() + "\n"


def generate(output_root: Path) -> tuple[Path, Path]:
    output_root.mkdir(parents=True, exist_ok=True)
    cli = output_root / "cli.md"
    mcp = output_root / "mcp-v2.md"
    cli.write_text(cli_reference(), encoding="utf-8")
    mcp.write_text(mcp_reference(), encoding="utf-8")
    return cli, mcp


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-root", type=Path, default=REPOSITORY / "docs" / "reference")
    args = parser.parse_args(argv)
    try:
        for path in generate(Path(args.output_root)):
            print(path.relative_to(REPOSITORY) if path.is_relative_to(REPOSITORY) else path)
    except (OSError, RuntimeError, subprocess.SubprocessError) as error:
        print(str(error), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
