"""Inward-facing dependency contracts and deterministic test implementations."""

from jaws.domain import Clock, IdGenerator

from .contracts import (
    ArtifactStore,
    EmbeddingProvider,
    EnrichmentProvider,
    Evaluator,
    EvidenceStore,
    PacketSource,
    Ranker,
    ReferenceBuilder,
)
from .fakes import (
    FakeEmbeddingProvider,
    FakeEnrichmentProvider,
    FakeEvaluator,
    FakeRanker,
    FakeReferenceBuilder,
    FrozenClock,
    InMemoryArtifactStore,
    InMemoryEvidenceStore,
    SequenceIdGenerator,
    SequencePacketSource,
)
from .inspection_fakes import InMemoryInspectionRepository
from .profile_fakes import InMemoryEnrichmentRepository, InMemoryProfileRepository
from .repositories import (
    CaptureNotFoundError,
    CaptureRepository,
    CaptureStateConflictError,
    DuplicateCaptureError,
    EnrichmentRepository,
    EntityNotFoundError,
    InactiveCaptureError,
    InspectionRepository,
    PacketRepository,
    ProfileRepository,
    ProfileScopeConflictError,
    RepositoryError,
    RepositorySchemaError,
)
from .repository_fakes import InMemoryCaptureRepository, InMemoryPacketRepository

__all__ = [
    "ArtifactStore",
    "CaptureNotFoundError",
    "CaptureRepository",
    "CaptureStateConflictError",
    "Clock",
    "EmbeddingProvider",
    "EnrichmentProvider",
    "Evaluator",
    "EvidenceStore",
    "DuplicateCaptureError",
    "EnrichmentRepository",
    "EntityNotFoundError",
    "FakeEmbeddingProvider",
    "FakeEnrichmentProvider",
    "FakeEvaluator",
    "FakeRanker",
    "FakeReferenceBuilder",
    "FrozenClock",
    "IdGenerator",
    "InMemoryArtifactStore",
    "InMemoryCaptureRepository",
    "InMemoryEvidenceStore",
    "InMemoryEnrichmentRepository",
    "InMemoryInspectionRepository",
    "InMemoryPacketRepository",
    "InMemoryProfileRepository",
    "InactiveCaptureError",
    "InspectionRepository",
    "PacketSource",
    "PacketRepository",
    "ProfileRepository",
    "ProfileScopeConflictError",
    "Ranker",
    "ReferenceBuilder",
    "RepositoryError",
    "RepositorySchemaError",
    "SequenceIdGenerator",
    "SequencePacketSource",
]
