"""Inward-facing dependency contracts and deterministic test implementations."""

from jaws.domain import Clock, IdGenerator

from .administration_fakes import InMemoryAdministrationRepository
from .contracts import (
    ArtifactStore,
    CancellationSignal,
    EmbeddingProvider,
    EnrichmentProvider,
    Evaluator,
    EvidenceStore,
    PacketSource,
    Ranker,
    ReferenceBuilder,
    WaitStrategy,
)
from .evidence_fakes import InMemoryEvidenceRepository
from .experiment_index_fakes import InMemoryExperimentIndexRepository
from .fakes import (
    FakeEmbeddingProvider,
    FakeEnrichmentProvider,
    FakeEvaluator,
    FakeRanker,
    FakeReferenceBuilder,
    FrozenClock,
    InMemoryArtifactStore,
    InMemoryEvidenceStore,
    RecordingWaitStrategy,
    SequenceCancellationSignal,
    SequenceIdGenerator,
    SequencePacketSource,
)
from .finding_index_fakes import InMemoryFindingRepository
from .inspection_fakes import InMemoryInspectionRepository
from .profile_fakes import InMemoryEnrichmentRepository, InMemoryProfileRepository
from .repositories import (
    AdministrationConflictError,
    AdministrationRepository,
    CaptureNotFoundError,
    CaptureRepository,
    CaptureStateConflictError,
    DuplicateCaptureError,
    DuplicateFindingError,
    DuplicateRunError,
    EnrichmentRepository,
    EntityNotFoundError,
    EvidenceImportConflictError,
    EvidenceRepository,
    EvidenceSchemaConflictError,
    ExperimentDigestConflictError,
    ExperimentIndexRepository,
    FindingIndexConflictError,
    FindingRepository,
    InactiveCaptureError,
    InspectionRepository,
    PacketRepository,
    ProfileRepository,
    ProfileScopeConflictError,
    RepositoryError,
    RepositorySchemaError,
    RetentionConflictError,
    RunNotFoundError,
    RunStateConflictError,
)
from .repository_fakes import InMemoryCaptureRepository, InMemoryPacketRepository

__all__ = [
    "AdministrationConflictError",
    "AdministrationRepository",
    "ArtifactStore",
    "CancellationSignal",
    "CaptureNotFoundError",
    "CaptureRepository",
    "CaptureStateConflictError",
    "Clock",
    "EmbeddingProvider",
    "EnrichmentProvider",
    "Evaluator",
    "EvidenceStore",
    "DuplicateCaptureError",
    "DuplicateRunError",
    "DuplicateFindingError",
    "EvidenceImportConflictError",
    "EvidenceRepository",
    "EvidenceSchemaConflictError",
    "EnrichmentRepository",
    "ExperimentDigestConflictError",
    "ExperimentIndexRepository",
    "FindingIndexConflictError",
    "FindingRepository",
    "EntityNotFoundError",
    "FakeEmbeddingProvider",
    "FakeEnrichmentProvider",
    "FakeEvaluator",
    "FakeRanker",
    "FakeReferenceBuilder",
    "FrozenClock",
    "IdGenerator",
    "InMemoryArtifactStore",
    "InMemoryAdministrationRepository",
    "InMemoryCaptureRepository",
    "InMemoryEvidenceRepository",
    "InMemoryExperimentIndexRepository",
    "InMemoryFindingRepository",
    "InMemoryEvidenceStore",
    "InMemoryEnrichmentRepository",
    "InMemoryInspectionRepository",
    "InMemoryPacketRepository",
    "InMemoryProfileRepository",
    "InactiveCaptureError",
    "InspectionRepository",
    "PacketSource",
    "PacketRepository",
    "ProfileRepository",
    "ProfileScopeConflictError",
    "Ranker",
    "ReferenceBuilder",
    "RecordingWaitStrategy",
    "RepositoryError",
    "RepositorySchemaError",
    "RetentionConflictError",
    "RunNotFoundError",
    "RunStateConflictError",
    "SequenceIdGenerator",
    "SequenceCancellationSignal",
    "SequencePacketSource",
    "WaitStrategy",
]
